<html>
    
      <head>
        <title>: Bristol City Council</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=320, target-densitydpi=device-dpi">
        <style type="text/css">          
          @media only screen and (max-width: 660px) {           
            table[class=w640],
            td[class=w640],
            img[class=w640] {
              width: 300px !important;
            }
            table[class*=hide],
            td[class*=hide],
            img[class*=hide],
            p[class*=hide],
            span[class*=hide] {
              display: none !important;
            }
            table[class=h0],
            td[class=h0] {
              height: 0 !important;
            }
            p[class=footer-content-left] {
              text-align: center !important;
            }
            #headline p {
              font-size: 24px !important;
            }
            .article-content {
              -webkit-text-size-adjust: 90% !important;
              -ms-text-size-adjust: 90% !important;
            }
            .header-content {
              -webkit-text-size-adjust: 80% !important;
              -ms-text-size-adjust: 80% !important;
            }
            img {
              height: auto;
              line-height: 100%;
            }
          }
    
          /* Client-specific Styles */
    
          #outlook a {
            padding: 0;
          }
    
          /* Force Outlook to provide a "view in browser" button. */
    
          body {
            width: 100% !important;
          }          
         
          body {
            background-color: #fff;
            margin: 0;
            padding: 0;
          }
    
          img {
            outline: none;
            text-decoration: none;
            display: block;
          }
    
          br,
          strong br,
          b br,
          em br,
          i br {
            line-height: 100%;
          }
    
          h1
    
          h1 a
    
          h1 a:active
    
          /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
    
          h1 a:visited
    
          /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
    
          table td,
          table tr {
            border-collapse: collapse;
          }
    
          }
    
          /* Body text color for the New Yahoo. This example sets the font of Yahoo's Shortcuts to black. */        
             
    
          /* Fonts and Content */
    
          body,
          td {
            font-family: Arial, 'Helvetica Neue', Helvetica, Geneva, sans-serif;
          }
    
          /* Prevent Webkit and Windows Mobile platforms from changing default font sizes on header and footer. */          
    
          .article-content a {
            color: #446eb2;
            text-decoration: underline;
          }
    
          .article-content img {
            max-width: 100%
          }      
    
        </style>
       
      </head>
    
      <body>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tbody>
            <tr>
              <td align="center" bgcolor="#ffffff">
                <table class="w640" style="margin:0 10px;" width="640" cellpadding="0" cellspacing="0" border="0">
                  <tbody>
                    <tr>
                      <td class="w640" width="640">
                        <table id="black-bar" class="w640" width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#000000" style="background-color: #000000;">
                          <tbody>
                            <tr>
                              <td class="w640" width="640" height="6"></td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" height="10"></td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" height="50">
                        <table class="w640" width="640">
                          <tbody>
                            <tr>
                              <td align="center"> <a class="logo" href="http://www.bristol.gov.uk" style="border:none; text-decoration: none; width:60px; height:60px; display:block;"> <img src="https://style.bristol.gov.uk/images/logo-bcc.png" alt="Bristol City Council logo" width="60" height="60" border="0"> </a>                            </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" height="10"></td>
                    </tr>
                    <tr>
                      <td class="w640" width="640">
                        <table id="top-bar" class="w640" width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#DDDDDD" style="background-color: #DDDDDD;">
                          <tbody>
                            <tr>
                              <td class="w640" width="640" height="2"></td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" height="30" colspan="3"></td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" colspan="3">
                        <!-- START editable -->
                        <div class="article-title" style=" font-size: 24px; color: #2e3137;"><strong></strong></div>
                        <!-- END editable -->
                      </td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" height="30" colspan="3"></td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" height="20" bgcolor="#ffffff"></td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" bgcolor="#ffffff" align="left">
                        <div class="article-content" style="font-size: 16px; line-height: 22px; color: #3c4147; margin-top: 0px; margin-bottom: 0px; font-family: Arial, 'Helvetica Neue', Helvetica, Geneva, sans-serif; -webkit-text-size-adjust: none; -ms-text-size-adjust: none;">
                          <!-- START editable --><h1>Thanks, we’ve received your application</h1>                          						  
                          
                        <p>UPN: ${yourAssessment.upn} </p>
        				<p>School: ${yourAssessment.schoolName}</p>
        				<p>Submitted on: ${submittedDate?string("dd/MM/yyyy")}</p>

						<p>We have received your application. This will be reviewed at the next Top Up panel. For further information about Top Up dates please visit
						<a href="https://www.bristol.gov.uk/bristol-local-offer/professionals/school-age/apply-for-additional-funding-for-pupils-with-very-complex-needs"  target="_blank" >Local Offer website.</a></p>						
						
                          <!-- END editable --><br> <br> Thanks, <br> <strong style="color:#bc0031;">Bristol City Council</strong> </div>
                      </td>
                    </tr>
                    
                    <tr>
                      <td class="w640" width="640" height="30" bgcolor="#ffffff"></td>
                    </tr>
                    <tr>
                      <td>
                        <table id="bottom-bar" class="w640" width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#cccccc" style="background-color: #cccccc;">
                          <tbody>
                            <tr>
                              <td class="w640" width="640" height="2"></td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" height="15" bgcolor="#ffffff"></td>
                    </tr>
                    <tr>
                      <td id="footer" class="w640" width="640" align="left">
                        <div class="article-meta" style="font-size: 13px; line-height: 20px; margin-top: 0;"> This email was sent by Bristol City Council. <br> <br> <a href="http://www.bristol.gov.uk">www.bristol.gov.uk</a> <br> <br> This is an automatically generated email – please do not reply to it. </div>
                      </td>
                    </tr>
                    <tr>
                      <td class="w640" width="640" height="30"></td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </body>
    
    </html>
    